#!/bin/sh

export PATH=/sbin:/bin

# Use a pathname, as new modutils don't look in the current dir by default
insmod ./snull.ko $*
ifconfig sn0 ${LOCAL0:-192.168.0.1}
ifconfig sn1 ${LOCAL1:-192.168.1.1}
